# Gavin lyons 05-2023
# Makefile to install library for Max7219 seven segment display
# URL: https://github.com/gavinlyonsrepo/MAX7219_7SEG_RPI
# Library is installed to /usr/lib and include files are placed at /usr/include.
# Uninstall and clean options provided

# == Options ==
# 1. make = compile library
# 2. make install = install library to filesystem may need sudo)
# 3. clean = deletes .o files generated by step 1 from build directory
# 4. make uninstall  = uninstalls library (may need sudo)
# =============

# Where you want it installed
PREFIX=/usr
# where to place the libray
LIBDIR=$(PREFIX)/lib
# library name
LIB=libMAX7219_7SEG_RPI
# shared library name
LIBNAME=$(LIB).so.1.0

MD=mkdir
SRC=src
OBJ=obj
SRCS = $(wildcard $(SRC)/*.cpp)
OBJS = $(patsubst $(SRC)%.cpp,  $(OBJ)/%.o, $(SRCS))

CXX=g++
CCFLAGS= -march=native -mtune=native -mcpu=native -Iinclude/
LDFLAGS= -lbcm2835

# make all
# reinstall the library after each recompilation
all: clean pre-build MAX7219_7SEG_RPI 

pre-build:
	@echo
	@echo "*****************"
	@echo "[MAKE LIBRARY]"
	@echo
	$(MD) -vp $(OBJ)

# Make the library
MAX7219_7SEG_RPI: $(OBJS)
	$(CXX) -shared -Wl,-soname,$(LIB).so.1 $(CCFLAGS) $(LDFLAGS)  -o ${LIBNAME} $^
	@echo "[DONE!]"

# Library parts
$(OBJ)/%.o: $(SRC)/%.cpp
	$(CXX) -Wall -fPIC -c $(CCFLAGS) $< -o $@

# Install the library to LIBPATH
install:
	@echo
	@echo "[INSTALL LIBRARY]"
	@if ( test ! -d $(PREFIX)/lib ) ; then mkdir -vp $(PREFIX)/lib ; fi
	@install -vm 0755 ${LIBNAME} ${LIBDIR}
	@ln -svf ${LIBDIR}/${LIBNAME} ${LIBDIR}/${LIB}.so.1
	@ln -svf ${LIBDIR}/${LIBNAME} ${LIBDIR}/${LIB}.so
	@ldconfig
	@rm -rvf ${LIB}.*
	@echo "*****************"
	@echo
	@echo "[INSTALL HEADERS]"
	@if ( test ! -d $(PREFIX)/include ) ; then mkdir -p $(PREFIX)/include ; fi
	@cp -vf  include/*.hpp $(PREFIX)/include

	@echo "[DONE!]"

# Uninstall the library
uninstall:
	@echo "******************"
	@echo "[UNINSTALL LIBRARY]"
	@rm -vf ${LIBDIR}/${LIB}.*

	@echo "[UNINSTALL HEADERS]"
	@rm -rvf  $(PREFIX)/include/MAX7219_7SEG_RP*.hpp
	@echo "[DONE!]"

# clear build files
clean:
	@echo "******************"
	@echo "[CLEAN OBJECT FILES]"
	rm -rvf $(OBJ)/*.o ${LIB}.*
	@echo "[DONE!]"
